SYNC_TABLE_STEPS = [
    ('teams', ['name', 'normalized_name', 'team_type', 'profile_url'], 'team_id', None),
    ('competitions', ['name', 'normalized_name', 'level', 'gender'], 'competition_id', None),
    ('seasons', ['label', 'start_year', 'end_year', 'team_id'], 'season_id', {'team_id': 'teams'}),
    (
        'season_competitions',
        ['season_id', 'competition_id', 'stage_label', 'source_path'],
        'season_competition_id',
        {'season_id': 'seasons', 'competition_id': 'competitions'},
    ),
    ('referees', ['name', 'normalized_name', 'profile_url'], 'referee_id', None),
    (
        'coaches',
        ['name', 'normalized_name', 'birth_date', 'birth_place', 'nationality', 'profile_url'],
        'coach_id',
        None,
    ),
    (
        'players',
        ['name', 'normalized_name', 'birth_date', 'birth_place', 'height_cm',
         'weight_kg', 'primary_position', 'nationality', 'profile_url', 'image_url'],
        'player_id',
        None,
    ),
    ('player_aliases', ['player_id', 'alias', 'normalized_alias'], 'alias_id', {'player_id': 'players'}),
    ('player_careers', ['player_id', 'team_name', 'start_year', 'end_year', 'notes'], 'career_id', {'player_id': 'players'}),
    ('coach_careers', ['coach_id', 'team_name', 'start_date', 'end_date', 'role'], 'career_id', {'coach_id': 'coaches'}),
    (
        'season_squads',
        ['season_competition_id', 'player_id', 'position_group', 'shirt_number', 'status', 'notes'],
        'season_squad_id',
        {'season_competition_id': 'season_competitions', 'player_id': 'players'},
    ),
    (
        'matches',
        ['season_competition_id', 'round_name', 'matchday', 'leg', 'match_date',
         'kickoff_time', 'venue', 'attendance', 'referee_id', 'home_team_id',
         'away_team_id', 'home_score', 'away_score', 'halftime_home', 'halftime_away',
         'extra_time_home', 'extra_time_away', 'penalties_home', 'penalties_away', 'source_file'],
        'match_id',
        {
            'season_competition_id': 'season_competitions',
            'referee_id': 'referees',
            'home_team_id': 'teams',
            'away_team_id': 'teams',
        },
    ),
    ('match_coaches', ['match_id', 'team_id', 'coach_id', 'role'], 'match_coach_id', {'match_id': 'matches', 'team_id': 'teams', 'coach_id': 'coaches'}),
    ('match_referees', ['match_id', 'referee_id', 'role'], 'match_referee_id', {'match_id': 'matches', 'referee_id': 'referees'}),
    (
        'match_lineups',
        ['match_id', 'team_id', 'player_id', 'shirt_number', 'is_starter',
         'minute_on', 'stoppage_on', 'minute_off', 'stoppage_off'],
        'lineup_id',
        {'match_id': 'matches', 'team_id': 'teams', 'player_id': 'players'},
    ),
    (
        'match_substitutions',
        ['match_id', 'team_id', 'minute', 'stoppage', 'player_on_id', 'player_off_id'],
        'substitution_id',
        {
            'match_id': 'matches',
            'team_id': 'teams',
            'player_on_id': 'players',
            'player_off_id': 'players',
        },
    ),
    (
        'goals',
        ['match_id', 'team_id', 'player_id', 'assist_player_id', 'minute',
         'stoppage', 'score_home', 'score_away', 'event_type'],
        'goal_id',
        {'match_id': 'matches', 'team_id': 'teams', 'player_id': 'players', 'assist_player_id': 'players'},
    ),
    ('cards', ['match_id', 'team_id', 'player_id', 'minute', 'stoppage', 'card_type'], 'card_id', {'match_id': 'matches', 'team_id': 'teams', 'player_id': 'players'}),
    ('match_notes', ['match_id', 'note', 'note_type'], 'note_id', {'match_id': 'matches'}),
    (
        'season_matchdays',
        ['season_competition_id', 'matchday', 'date', 'position', 'points', 'goals_for', 'goals_against', 'goal_difference'],
        'season_matchday_id',
        {'season_competition_id': 'season_competitions'},
    ),
]
